project:
  type: website

website:
  title: "HillmanAnalytics.com"
  #navbar:
   #left:
    # - href: index.qmd
    #   text: Home
  
format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

